apiVersion: v2
type: application
name: secrets-stack
version: 0.1.0 
appVersion: 0.1.0 
dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.27.0
    alias: vault
  - name: external-secrets
    alias: eso
    repository: https://charts.external-secrets.io
    version: 0.9.13
