apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault

spec:
  provider:
    vault:
      server: http://{{ .Values.name }}-vault:8200
      path: "secret"
      version: "v1"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes/internal"
          # A required field containing the Vault Role to assume.
          role: "eso-creds-reader"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "auth-sa"
            namespace: "{{ .Values.name }}"
          # Optional secret field containing a Kubernetes ServiceAccount JWT
          #  used for authenticating with Vault
          secretRef:
            name: "auth-sa-token"
            key: "token"
            namespace: "{{ .Values.name }}"
