apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "{{ .Values.name }}"
metadata:
  name: templates
commonLabels:
  app.kubernetes.io/name: "{{ .Values.name }}"
  helm.sh/chart: "{{ .Chart.Name }}-{{ .Values.checksum }}" 
  app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  app.kubernetes.io/instance: "{{ .Release.Name }}"
  app.kubernetes.io/version: "{{ .Values.checksum }}"
  app.kubernetes.io/component: secrets

resources:
- serviceaccount.auth-sa.yaml
- secret.auth-sa-token.yaml
- clusterrolebinding.role-tokenreview-binding.yaml
- clustersecretsstore.vault.yaml
