apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "{{ .Values.name }}"
metadata:
  name: templates
commonLabels:
  app.kubernetes.io/name: "{{ .Values.name }}"
  app.kubernetes.io/version: "{{ .Values.checksum }}"
  app.kubernetes.io/instance: "{{ .Values.name }}-{{ .Values.checksum }}"
  app.kubernetes.io/part-of: "{{ .Values.name }}"  
  app.kubernetes.io/managed-by: Helm  

commonAnnotations:
  "meta.helm.sh/release-name": "{{ .Values.name }}"
    
resources:
- serviceaccount.auth-sa.yaml
- secret.auth-sa-token.yaml
- clusterrolebinding.role-tokenreview-binding.yaml
- clustersecretsstore.vault.yaml
- clusterexternalsecret.checksum.yaml
- tests
