apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: templates
resources:
- serviceaccount.auth-sa.yaml
- secret.auth-sa-token.yaml
- clusterrolebinding.role-tokenreview-binding.yaml
