apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crds
commonLabels:
  app.kubernetes.io/name: esovault
  app.kubernetes.io/version: "{{ .Values.checksum }}"
  app.kubernetes.io/managed-by: Helm  
commonAnnotations:
  "meta.helm.sh/release-name": "{{ .Values.name }}"
    
resources:
- clustersecretsstore.vault.yaml
- clusterexternalsecret.checksum.yaml
